// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjmU9b7trS15dH-amLSYWf349Q0EIpbS0',
    appId: '1:24097679071:web:cb25e90a9a06b7e7e4ab6a',
    messagingSenderId: '24097679071',
    projectId: 'dhigrowth-hotal-managamenet',
    authDomain: 'dhigrowth-hotal-managamenet.firebaseapp.com',
    storageBucket: 'dhigrowth-hotal-managamenet.firebasestorage.app',
    measurementId: 'G-FR45Q25E02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV3og3scTl24mN_V-rtywp10BHjcVCCiI',
    appId: '1:24097679071:android:5ca824b3271886fee4ab6a',
    messagingSenderId: '24097679071',
    projectId: 'dhigrowth-hotal-managamenet',
    storageBucket: 'dhigrowth-hotal-managamenet.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjmU9b7trS15dH-amLSYWf349Q0EIpbS0',
    appId: '1:24097679071:web:4aa4b8c922a0ea0ae4ab6a',
    messagingSenderId: '24097679071',
    projectId: 'dhigrowth-hotal-managamenet',
    authDomain: 'dhigrowth-hotal-managamenet.firebaseapp.com',
    storageBucket: 'dhigrowth-hotal-managamenet.firebasestorage.app',
    measurementId: 'G-9NS0494B1Q',
  );
}
